import type { Metadata } from "next";
import { Inter} from "next/font/google";


const inter=Inter({subsets:['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div 
        className='flex h-screen flex-col'
          >
              root
       <main className="flex-1-wrapper">{children}</main> 
      </div>
    </html>
  );
}
